version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: goldenratioboy/flask-api-container
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and Push Docker image
          command:
            docker build -t goldenratioboy/$IMAGE_NAME .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push goldenratioboy/$IMAGE_NAME

workflows:
  main:
    jobs:
      - build