version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      # Startup Docker
      - persist_to_workspace:
          root: ~/app
          paths:
            - null
      - run:
          command: |
            docker info
            docker build -t flask-api .
      #Deploy Docker image
      - run: 
          command: |
            docker login --username=$DOCKER_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            docker tag flask-api registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
      - run:
          name: Test docker image before deploying
          command: |
            cd ../test

      - run: 
          name: Setup Heroku
          command: |
            chmod +x .circleci/heroku-setup.sh
            .circleci/heroku-setup.sh
      - run:
          name: Deploy to Heroku
          command: |
            heroku container:release web -a $HEROKU_APP_NAME